version: "2.1"
services:
  db_mysql:
    image: "mysql:latest"
    container_name: "db_mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cobaalta"
    # ports:
    #   - "3307:3306"
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-proot", "-e", "show schemas"]
      interval: 5s

  api-praktikum:
    image: "rafliferdian/praktikum-cicd:v1.0.0"
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    environment:
      DB_HOST: "db_mysql"
      DB_USERNAME: "root"
      DB_PASSWORD: "root"
      DB_NAME: "cobaalta"
      DB_PORT: "3306"
      APIPort: ":8000"
    depends_on:
      db_mysql:
        condition: service_healthy
