name: ini CD golang
on:
  push:
    branches:
      - "main"
jobs:
  testing:
    runs-on: ubuntu-latest
    name: "ini unitest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: run unit test
        run: go test -v ./...
      - name: run linting
        uses: golangci/golangci-lint-action@v3

  deploy:
    runs-on: ubuntu-latest
    name: "ini deploy"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rafliferdian/praktikum-cicd:latest

      - name: update aws instance
        uses: appleboy/ssh-action@master
        with:
          host: ec2-54-169-8-99.ap-southeast-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.KEY_AWS }}
          port: 22
          script: |
#            1. ngeremove image latest
            sudo docker stop app
            sudo docker container rm app
#            2. nge pull image latest
            sudo docker pull rafliferdian/praktikum-cicd:latest
#            3. rerun
            sudo docker run -d -v $PWD/.env:/.env -p 80:6969 --name app rafliferdian/praktikum-cicd:latest